name: Build

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
    contents: read
    packages: write

jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Builder
              uses: docker/setup-buildx-action@v3

            - name: Log into GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Dockerfile
                  push: false
                  tags: ghcr.io/${{ github.repository }}:latest

            - name: Push to Github Container Registry
              if: github.event_name == 'push'
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: ghcr.io/${{ github.repository }}:latest
